version: '3'
services:
  client:
   build: ./app
   ports:
     - '80:80'
   depends_on:
     - api
   networks:
     - todo-network
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - todo-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo
    networks:
      - todo-network
networks:
  todo-network:

